#!/bin/sh

APPDIR=$(dirname "$0")
java  -Djava.library.path="$APPDIR:$APPDIR/lib" -cp "$APPDIR/lib/HomeLESS_Hit_Analyzer.jar:$APPDIR/lib/core.jar:$APPDIR/lib/jogl-all.jar:$APPDIR/lib/gluegen-rt.jar:$APPDIR/lib/jogl-all-natives-linux-i586.jar:$APPDIR/lib/gluegen-rt-natives-linux-i586.jar:$APPDIR/lib/GSVideo.jar:$APPDIR/lib/gstreamer-java.jar:$APPDIR/lib/jna.jar:$APPDIR/lib/guicomponents.jar:$APPDIR/lib/controlP5.jar" HomeLESS_Hit_Analyzer "$@"
